import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import Link from 'next/link';
import { Tab } from '@headlessui/react';
import Masonry from 'react-masonry-css';
import classNames from 'classnames';
import { useRef } from 'react';

import ocean1 from '../public/ocean1.webp';
import ocean2 from '../public/ocean2.webp';
import ocean3 from '../public/ocean3.webp';
import ocean4 from '../public/ocean4.webp';
import ocean5 from '../public/ocean5.webp';
import bgImage from '../public/photography-bg.webp';

import LightGalleryComponent from 'lightgallery/react';
import { LightGallery } from 'lightgallery/lightgallery';

// import styles
import 'lightgallery/css/lightgallery.css';
import 'lightgallery/css/lg-zoom.css';
import 'lightgallery/css/lg-thumbnail.css';

// import plugins if you need
import lgThumbnail from 'lightgallery/plugins/thumbnail';
import lgZoom from 'lightgallery/plugins/zoom';

const inter = Inter({ subsets: ['latin'] })

const tabs = [
  {
    key: 'all',
    display: 'All',
  },
  {
    key: 'oceans',
    display: 'Oceans'
  },
  {
    key: 'forests',
    display: 'Forests'
  }
]

const images = [
  ocean1,
  ocean2,
  ocean3,
  ocean4,
  ocean5
]


export default function Home() {

  const lightboxRef = useRef<LightGallery | null>(null)

  return (
    <div className="h-full overflow-auto">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      < Image
        src={bgImage}
        alt="#"
        className="fixed top-0 left-0 w-full h-full"
        placeholder='blur'
      ></Image>

      <div className="fixed left-0 top-0 w-full h-full bg-gradient-to-t from-stone-900" />
      <header className="fixed w-full z-10 top-0 flex justify-between items-center h-[90px] px-6 bg-stone-900">
        <span className="uppercase text-lg font-medium px-10">Photography Portfolio</span>
        <Link href="#" className="rounded-3xl bg-white text-stone-700 px-3 py-2 hover:bg-opacity-90">
          Get in touch
        </Link>
      </header>
      <main className="relative pt-[110px]">
        <div className="flex flex-col items-center h-full">
          <Tab.Group>
            <Tab.List className="flex items-center gap-12">
              {tabs.map((tab) =>
                <Tab key={tab.key} className="p-2">{({ selected }) => <span className={classNames("uppercase text-lg", selected ? 'text-white' : 'text-stone-600')}>{tab.display}</span>}</Tab>
              )}
            </Tab.List>
            <Tab.Panels className="h-full max-w-[900px] w-full p-2 sm:p-4 my-6">
              <Tab.Panel className="">
                <Masonry breakpointCols={2} className="flex gap-4">
                  {images.map((image, index) =>
                    < Image
                      key={image}
                      src={image}
                      alt="#"
                      className="mb-4 hover:opacity-70 cursor-pointer"
                      placeholder='blur'
                      onClick={() => { lightboxRef.current?.openGallery(index) }}
                    ></Image>
                  )}
                </Masonry>
                <LightGalleryComponent
                  onInit={(ref) => {
                    if (ref) {
                      lightboxRef.current = ref.instance;
                    }
                  }
                  }
                  speed={500}
                  download={false}
                  dynamic
                  dynamicEl={images.map((image) => ({
                    src: image.src,
                    thumb: image.src
                  }))
                  }
                  plugins={[lgThumbnail, lgZoom]}
                >
                  ...
                </LightGalleryComponent>
              </Tab.Panel>
              <Tab.Panel>Oceans</Tab.Panel>
              <Tab.Panel>Forests</Tab.Panel>
            </Tab.Panels>
          </Tab.Group>
        </div>
      </main >
      <footer className="relative flex justify-center items-center h-[90px] uppercase text-lg font-medium">
        <p>Photography Portfolio</p>
      </footer>
    </div >
  )
}
